### ISSUE TITLE
Erros encontrados no teste

### ISSUE THREAD

**Issue by guiBiagini** [Lucas-Angelo/pizzaria#43]
![WhatsApp Image 2022-10-11 at 12 19 55](https://user-images.githubusercontent.com/38760047/195186981-9e6f3060-b64b-4e52-8145-974f488ac41b.jpeg)

**Comment by guiBiagini** [comment]
![WhatsApp Image 2022-10-11 at 12 20 09](https://user-images.githubusercontent.com/38760047/195187130-21fcac77-26f6-408a-888d-812eeba13592.jpeg)

**Comment by Lucas-Angelo** [comment]
@guiBiagini no requisito era necessário preencher número de celular? Até onde foi especificado era para definir apenas se foi um pedido feito por celular ou presencialmente. 
Em relação ao nome da Pizza, consideramos como um campo unique, é de boa prática não permitir a alteração de um campo único.

**Comment by Lucas-Angelo** [comment]
> @guiBiagini no requisito era necessário preencher número de celular? Até onde foi especificado era para definir apenas se foi um pedido feito por celular ou presencialmente. Em relação ao nome da Pizza, consideramos como um campo unique, é de boa prática não permitir a alteração de um campo único.

![image](https://user-images.githubusercontent.com/49598959/195208378-ca4f03f9-d89c-4dcd-bed7-37d1b7500d16.png)
![image](https://user-images.githubusercontent.com/49598959/195208656-fa52f5c7-7397-4d93-9cba-a9c85bc7e156.png)
@guiBiagini
